import type {
  Category,
  Brand,
  Product,
  Review,
  Address,
  Order,
  ShippingMethod,
  PaymentMethod,
  Coupon,
} from '@/types/storefront';

export const CURRENCY = {
  code: 'BDT',
  symbol: '৳',
  position: 'left' as const,
};

export { formatMoney, formatMoneyDecimal } from '@/lib/utils/format';

export const STORE_INFO = {
  name: 'UIMS Store',
  tagline: 'Quality products, delivered fast',
  email: 'support@uims.shop',
  phone: '+880 1700-000000',
  address: 'House 12, Road 5, Dhanmondi, Dhaka 1205, Bangladesh',
  currency: CURRENCY,
  freeShippingThreshold: 5000,
  defaultDeliveryDays: 3,
  taxRate: 5,
};

export const CATEGORIES: Category[] = [
  {
    id: 'c-electronics',
    name: 'Electronics',
    slug: 'electronics',
    image:
      'https://images.unsplash.com/photo-1593344484962-796055d4a3a4?w=400&h=400&fit=crop',
    productCount: 248,
  },
  {
    id: 'c-mobile',
    name: 'Mobile',
    slug: 'mobile',
    image:
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop',
    parentId: 'c-electronics',
    productCount: 86,
  },
  {
    id: 'c-smartphones',
    name: 'Smartphones',
    slug: 'smartphones',
    parentId: 'c-mobile',
    productCount: 42,
  },
  {
    id: 'c-cases',
    name: 'Cases & Covers',
    slug: 'cases',
    parentId: 'c-mobile',
    productCount: 24,
  },
  {
    id: 'c-laptop',
    name: 'Laptop',
    slug: 'laptop',
    image:
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop',
    parentId: 'c-electronics',
    productCount: 54,
  },
  {
    id: 'c-audio',
    name: 'Audio',
    slug: 'audio',
    image:
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop',
    parentId: 'c-electronics',
    productCount: 38,
  },
  {
    id: 'c-wearable',
    name: 'Wearable',
    slug: 'wearable',
    image:
      'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=400&h=400&fit=crop',
    parentId: 'c-electronics',
    productCount: 22,
  },
  {
    id: 'c-fashion',
    name: 'Fashion',
    slug: 'fashion',
    image:
      'https://images.unsplash.com/photo-1445205170230-053b83016050?w=400&h=400&fit=crop',
    productCount: 312,
  },
  {
    id: 'c-men',
    name: 'Men',
    slug: 'men',
    parentId: 'c-fashion',
    productCount: 124,
  },
  {
    id: 'c-women',
    name: 'Women',
    slug: 'women',
    parentId: 'c-fashion',
    productCount: 156,
  },
  {
    id: 'c-shoes',
    name: 'Shoes',
    slug: 'shoes',
    parentId: 'c-fashion',
    productCount: 32,
  },
  {
    id: 'c-grocery',
    name: 'Grocery',
    slug: 'grocery',
    image:
      'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&h=400&fit=crop',
    productCount: 184,
  },
  {
    id: 'c-home',
    name: 'Home & Living',
    slug: 'home',
    image:
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop',
    productCount: 96,
  },
  {
    id: 'c-beauty',
    name: 'Beauty',
    slug: 'beauty',
    image:
      'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=400&fit=crop',
    productCount: 78,
  },
  {
    id: 'c-sports',
    name: 'Sports',
    slug: 'sports',
    image:
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop',
    productCount: 64,
  },
];

export const BRANDS: Brand[] = [
  { id: 'b-apple', name: 'Apple', slug: 'apple', productCount: 28 },
  { id: 'b-samsung', name: 'Samsung', slug: 'samsung', productCount: 42 },
  { id: 'b-xiaomi', name: 'Xiaomi', slug: 'xiaomi', productCount: 35 },
  { id: 'b-sony', name: 'Sony', slug: 'sony', productCount: 24 },
  { id: 'b-logitech', name: 'Logitech', slug: 'logitech', productCount: 18 },
  { id: 'b-jbl', name: 'JBL', slug: 'jbl', productCount: 16 },
  { id: 'b-nike', name: 'Nike', slug: 'nike', productCount: 32 },
  { id: 'b-adidas', name: 'Adidas', slug: 'adidas', productCount: 28 },
  { id: 'b-zara', name: "Zara", slug: 'zara', productCount: 22 },
  { id: 'b-anker', name: 'Anker', slug: 'anker', productCount: 14 },
];

const img = (id: string, q = 80) =>
  `https://images.unsplash.com/photo-${id}?w=${q * 8}&h=${q * 8}&fit=crop&auto=format`;

const PHOTOS = {
  iphone15: '1592899677977-9c10ca588bbd',
  iphone14: '1601784551446-20c9e07cdbdb',
  galaxy: '1610945415295-d9bbf067e59c',
  macbook: '1517336714731-489689fd1ca8',
  airpods: '1606220588913-b3aacb4d2f46',
  sony: '1583394838336-acd977736f90',
  watch: '1546868871-7041f2a55e12',
  mouse: '1527864550417-7fd91fc51a46',
  keyboard: '1587829741301-dc798b83add3',
  cable: '1583863788434-e58a36330cf0',
  charger: '1591815302525-756a9bcc3425',
  speaker: '1608043152269-423dbba4e7e1',
  shirt: '1602810318383-e386cc2a3ccf',
  shoes: '1542291026-7eec264c27ff',
  bag: '1548036328-c9fa89d128fa',
  tshirt: '1521572163474-6864f9cf17ab',
  watch2: '1523275335684-37898b6baf30',
  lipstick: '1586495777744-4413f21062fa',
  perfume: '1541643600914-78b084683601',
  coffee: '1559056199-641a0ac8b55e',
  snack: '1599490659213-e2b9527bd087',
  oil: '1474979266404-7eaacbcd87c5',
  sofa: '1555041469-a586c61ea9bc',
  lamp: '1507473885765-e6ed057f782c',
  plant: '1485955900006-10f4d324d411',
  yoga: '1545205597-3d9d02c29597',
  dumbbell: '1517836357463-d25dfeac3438',
  bike: '1571333250630-f0230c320b6d',
};

export const PRODUCTS: Product[] = [
  {
    id: 'p-001',
    name: 'iPhone 15 Pro 256GB',
    slug: 'iphone-15-pro-256gb',
    shortDescription: 'Titanium design, A17 Pro chip, ProRAW photography',
    description:
      'iPhone 15 Pro features a strong and light aerospace-grade titanium design with a textured matte glass back. The Action button replaces the Ring/Silent switch, offering a fast way to access your favorite feature. The new A17 Pro chip delivers groundbreaking performance. The 48MP Main camera is more advanced than ever, capturing super-high-resolution photos with stunning detail and color.',
    category: CATEGORIES[2],
    brand: BRANDS[0],
    images: [img(PHOTOS.iphone15), img(PHOTOS.iphone14), img(PHOTOS.airpods), img(PHOTOS.watch)],
    variations: [
      {
        id: 'v-001-256',
        productId: 'p-001',
        sku: 'IPH-15PRO-256-NT',
        name: '256GB - Natural Titanium',
        sellingPrice: 999,
        mrp: 1099,
        stock: 15,
        attributes: { Storage: '256GB', Color: 'Natural Titanium' },
        image: img(PHOTOS.iphone15),
        isDefault: true,
      },
      {
        id: 'v-001-512',
        productId: 'p-001',
        sku: 'IPH-15PRO-512-BL',
        name: '512GB - Blue Titanium',
        sellingPrice: 1199,
        mrp: 1299,
        stock: 8,
        attributes: { Storage: '512GB', Color: 'Blue Titanium' },
        image: img(PHOTOS.iphone15),
      },
      {
        id: 'v-001-1tb',
        productId: 'p-001',
        sku: 'IPH-15PRO-1TB-BK',
        name: '1TB - Black Titanium',
        sellingPrice: 1499,
        mrp: 1599,
        stock: 4,
        attributes: { Storage: '1TB', Color: 'Black Titanium' },
        image: img(PHOTOS.iphone15),
      },
    ],
    rating: 4.8,
    reviewCount: 124,
    isFeatured: true,
    isNew: true,
    isBestseller: true,
    isOnSale: true,
    freeShipping: true,
    estimatedDeliveryDays: 2,
  },
  {
    id: 'p-002',
    name: 'Samsung Galaxy S24 Ultra',
    slug: 'samsung-galaxy-s24-ultra',
    shortDescription: 'Galaxy AI, 200MP camera, S Pen included',
    description:
      'Meet Galaxy S24 Ultra, the ultimate form of Galaxy Ultra with a new titanium exterior and a 6.8" flat display. The new Galaxy AI suite is here. Built-in S Pen writes a whole new chapter. The 200MP wide camera captures reality with incredible detail.',
    category: CATEGORIES[2],
    brand: BRANDS[1],
    images: [img(PHOTOS.galaxy), img(PHOTOS.iphone15), img(PHOTOS.watch)],
    variations: [
      {
        id: 'v-002-256',
        productId: 'p-002',
        sku: 'SGS24U-256-TI',
        name: '256GB - Titanium Gray',
        sellingPrice: 1199,
        mrp: 1299,
        stock: 12,
        attributes: { Storage: '256GB', Color: 'Titanium Gray' },
        image: img(PHOTOS.galaxy),
        isDefault: true,
      },
      {
        id: 'v-002-512',
        productId: 'p-002',
        sku: 'SGS24U-512-BK',
        name: '512GB - Titanium Black',
        sellingPrice: 1419,
        mrp: 1519,
        stock: 7,
        attributes: { Storage: '512GB', Color: 'Titanium Black' },
        image: img(PHOTOS.galaxy),
      },
    ],
    rating: 4.7,
    reviewCount: 89,
    isFeatured: true,
    isNew: true,
    isBestseller: true,
    freeShipping: true,
    estimatedDeliveryDays: 3,
  },
  {
    id: 'p-003',
    name: 'MacBook Pro 14" M3 Pro',
    slug: 'macbook-pro-14-m3-pro',
    shortDescription: '18hr battery, Liquid Retina XDR, M3 Pro chip',
    description:
      'Supercharged by M3 Pro, MacBook Pro features a brilliant Liquid Retina XDR display, a wide array of ports, and up to 18 hours of battery life. The Magic Keyboard with Touch ID delivers a fast, easy, and secure way to unlock your Mac and sign in to apps and sites.',
    category: CATEGORIES[4],
    brand: BRANDS[0],
    images: [img(PHOTOS.macbook), img(PHOTOS.keyboard), img(PHOTOS.mouse)],
    variations: [
      {
        id: 'v-003-512',
        productId: 'p-003',
        sku: 'MBP14-M3PRO-512',
        name: '512GB SSD - Space Black',
        sellingPrice: 1999,
        mrp: 2199,
        stock: 6,
        attributes: { Storage: '512GB', Color: 'Space Black' },
        image: img(PHOTOS.macbook),
        isDefault: true,
      },
      {
        id: 'v-003-1tb',
        productId: 'p-003',
        sku: 'MBP14-M3PRO-1TB',
        name: '1TB SSD - Silver',
        sellingPrice: 2399,
        mrp: 2599,
        stock: 3,
        attributes: { Storage: '1TB', Color: 'Silver' },
        image: img(PHOTOS.macbook),
      },
    ],
    rating: 4.9,
    reviewCount: 67,
    isFeatured: true,
    isBestseller: true,
    freeShipping: true,
    estimatedDeliveryDays: 4,
  },
  {
    id: 'p-004',
    name: 'Sony WH-1000XM5 Wireless Headphones',
    slug: 'sony-wh-1000xm5',
    shortDescription: 'Industry-leading noise cancellation, 30hr battery',
    description:
      'Industry-leading noise canceling with Auto NC Optimizer. Crystal clear hands-free calling, with 4 beamforming microphones. Up to 30-hour battery life with quick charging. Ultra-comfortable, lightweight design.',
    category: CATEGORIES[5],
    brand: BRANDS[3],
    images: [img(PHOTOS.sony), img(PHOTOS.airpods), img(PHOTOS.speaker)],
    variations: [
      {
        id: 'v-004-bk',
        productId: 'p-004',
        sku: 'WH1000XM5-BK',
        name: 'Black',
        sellingPrice: 349,
        mrp: 399,
        stock: 22,
        attributes: { Color: 'Black' },
        image: img(PHOTOS.sony),
        isDefault: true,
      },
      {
        id: 'v-004-sl',
        productId: 'p-004',
        sku: 'WH1000XM5-SL',
        name: 'Silver',
        sellingPrice: 349,
        mrp: 399,
        stock: 14,
        attributes: { Color: 'Silver' },
        image: img(PHOTOS.sony),
      },
    ],
    rating: 4.7,
    reviewCount: 312,
    isFeatured: true,
    isBestseller: true,
    isOnSale: true,
    freeShipping: true,
    estimatedDeliveryDays: 2,
  },
  {
    id: 'p-005',
    name: 'Apple AirPods Pro (2nd Gen)',
    slug: 'apple-airpods-pro-2',
    shortDescription: 'Adaptive Audio, Active Noise Cancellation',
    description:
      'AirPods Pro feature the H2 chip for up to 2x more Active Noise Cancellation. Adaptive Audio dynamically blends Active Noise Cancellation and Transparency mode. Personalized Spatial Audio surrounds you in sound.',
    category: CATEGORIES[5],
    brand: BRANDS[0],
    images: [img(PHOTOS.airpods), img(PHOTOS.sony)],
    variations: [
      {
        id: 'v-005-usbc',
        productId: 'p-005',
        sku: 'APP2-USBC',
        name: 'USB-C MagSafe Case',
        sellingPrice: 229,
        mrp: 249,
        stock: 35,
        attributes: { Case: 'USB-C MagSafe' },
        image: img(PHOTOS.airpods),
        isDefault: true,
      },
    ],
    rating: 4.8,
    reviewCount: 542,
    isBestseller: true,
    isOnSale: true,
    freeShipping: true,
    estimatedDeliveryDays: 1,
  },
  {
    id: 'p-006',
    name: 'Apple Watch Series 9',
    slug: 'apple-watch-series-9',
    shortDescription: 'S9 chip, Double Tap, Always-On Retina',
    description:
      'Apple Watch Series 9 features the new S9 SiP and a magical new way to use your watch — Double Tap. The most popular smartwatch in the world. Now with new colors and an iconic new way to use it.',
    category: CATEGORIES[6],
    brand: BRANDS[0],
    images: [img(PHOTOS.watch), img(PHOTOS.watch2)],
    variations: [
      {
        id: 'v-006-41',
        productId: 'p-006',
        sku: 'AW9-41-PK',
        name: '41mm - Pink Aluminum',
        sellingPrice: 399,
        mrp: 429,
        stock: 18,
        attributes: { Size: '41mm', Color: 'Pink' },
        image: img(PHOTOS.watch),
        isDefault: true,
      },
      {
        id: 'v-006-45',
        productId: 'p-006',
        sku: 'AW9-45-MN',
        name: '45mm - Midnight Aluminum',
        sellingPrice: 429,
        mrp: 459,
        stock: 11,
        attributes: { Size: '45mm', Color: 'Midnight' },
        image: img(PHOTOS.watch),
      },
    ],
    rating: 4.6,
    reviewCount: 234,
    isNew: true,
    isFeatured: true,
    freeShipping: true,
    estimatedDeliveryDays: 2,
  },
  {
    id: 'p-007',
    name: 'Logitech MX Master 3S',
    slug: 'logitech-mx-master-3s',
    shortDescription: '8K DPI, Quiet Clicks, Multi-device',
    description:
      'The Master Series by Logitech — MX Master 3S. Ultra-fast scrolling, ergonomic design, and 8K DPI tracking on any surface, even glass. Quiet Clicks deliver a satisfying feel with 90% less click noise.',
    category: CATEGORIES[5],
    brand: BRANDS[4],
    images: [img(PHOTOS.mouse), img(PHOTOS.keyboard)],
    variations: [
      {
        id: 'v-007-gy',
        productId: 'p-007',
        sku: 'MX3S-GY',
        name: 'Graphite',
        sellingPrice: 99,
        mrp: 119,
        stock: 45,
        attributes: { Color: 'Graphite' },
        image: img(PHOTOS.mouse),
        isDefault: true,
      },
    ],
    rating: 4.8,
    reviewCount: 678,
    isBestseller: true,
    isOnSale: true,
    freeShipping: true,
    estimatedDeliveryDays: 1,
  },
  {
    id: 'p-008',
    name: 'Anker USB-C Cable 2m (2-Pack)',
    slug: 'anker-usb-c-cable-2m',
    shortDescription: '60W Power Delivery, Braided Nylon',
    description:
      'Premium USB-C to USB-C cables with 60W Power Delivery for fast charging. Braided nylon construction for 30,000+ bend lifespan. Compatible with phones, tablets, and laptops.',
    category: CATEGORIES[5],
    brand: BRANDS[9],
    images: [img(PHOTOS.cable), img(PHOTOS.charger)],
    variations: [
      {
        id: 'v-008-2pk',
        productId: 'p-008',
        sku: 'ANK-USBC-2M-2PK',
        name: '2m - 2 Pack',
        sellingPrice: 19,
        mrp: 29,
        stock: 156,
        attributes: { Length: '2m', Quantity: '2 Pack' },
        image: img(PHOTOS.cable),
        isDefault: true,
      },
    ],
    rating: 4.5,
    reviewCount: 1024,
    isOnSale: true,
    freeShipping: false,
    estimatedDeliveryDays: 2,
  },
  {
    id: 'p-009',
    name: 'Nike Air Max 270',
    slug: 'nike-air-max-270',
    shortDescription: 'Iconic Air Max heel, all-day comfort',
    description:
      'The Nike Air Max 270 combines two of our most iconic innovations for incredible comfort. The tallest Max Air unit yet delivers an incredibly soft underfoot feel while the stretchy inner sleeve and padded collar provide a snug, comfortable fit.',
    category: CATEGORIES[10],
    brand: BRANDS[6],
    images: [img(PHOTOS.shoes), img(PHOTOS.bag)],
    variations: [
      {
        id: 'v-009-42',
        productId: 'p-009',
        sku: 'NAM270-42-BK',
        name: 'Size 42 - Black',
        sellingPrice: 149,
        mrp: 179,
        stock: 28,
        attributes: { Size: '42', Color: 'Black' },
        image: img(PHOTOS.shoes),
        isDefault: true,
      },
      {
        id: 'v-009-43',
        productId: 'p-009',
        sku: 'NAM270-43-WH',
        name: 'Size 43 - White',
        sellingPrice: 149,
        mrp: 179,
        stock: 32,
        attributes: { Size: '43', Color: 'White' },
        image: img(PHOTOS.shoes),
      },
    ],
    rating: 4.6,
    reviewCount: 89,
    isBestseller: true,
    freeShipping: true,
    estimatedDeliveryDays: 3,
  },
  {
    id: 'p-010',
    name: "Men's Classic Oxford Shirt",
    slug: 'mens-classic-oxford-shirt',
    shortDescription: 'Premium cotton, slim fit, all-day comfort',
    description:
      'A timeless oxford shirt crafted from 100% premium cotton. Slim fit cut, button-down collar, single chest pocket. Perfect for both office and casual wear.',
    category: CATEGORIES[8],
    brand: BRANDS[8],
    images: [img(PHOTOS.shirt), img(PHOTOS.tshirt)],
    variations: [
      {
        id: 'v-010-m-wh',
        productId: 'p-010',
        sku: 'OX-M-WH',
        name: 'M - White',
        sellingPrice: 45,
        mrp: 59,
        stock: 42,
        attributes: { Size: 'M', Color: 'White' },
        image: img(PHOTOS.shirt),
        isDefault: true,
      },
      {
        id: 'v-010-l-bl',
        productId: 'p-010',
        sku: 'OX-L-BL',
        name: 'L - Blue',
        sellingPrice: 45,
        mrp: 59,
        stock: 38,
        attributes: { Size: 'L', Color: 'Blue' },
        image: img(PHOTOS.shirt),
      },
    ],
    rating: 4.4,
    reviewCount: 156,
    isOnSale: true,
    freeShipping: false,
    estimatedDeliveryDays: 3,
  },
  {
    id: 'p-011',
    name: 'Premium Leather Backpack',
    slug: 'premium-leather-backpack',
    shortDescription: 'Genuine leather, laptop compartment',
    description:
      'Handcrafted from genuine full-grain leather. Fits up to 15" laptop. Multiple compartments for organized storage. Adjustable padded straps for all-day comfort.',
    category: CATEGORIES[10],
    brand: BRANDS[8],
    images: [img(PHOTOS.bag), img(PHOTOS.shoes)],
    variations: [
      {
        id: 'v-011-brn',
        productId: 'p-011',
        sku: 'LBP-BRN',
        name: 'Brown',
        sellingPrice: 189,
        mrp: 249,
        stock: 15,
        attributes: { Color: 'Brown' },
        image: img(PHOTOS.bag),
        isDefault: true,
      },
      {
        id: 'v-011-bk',
        productId: 'p-011',
        sku: 'LBP-BK',
        name: 'Black',
        sellingPrice: 189,
        mrp: 249,
        stock: 12,
        attributes: { Color: 'Black' },
        image: img(PHOTOS.bag),
      },
    ],
    rating: 4.7,
    reviewCount: 67,
    isFeatured: true,
    isNew: true,
    isOnSale: true,
    freeShipping: true,
    estimatedDeliveryDays: 3,
  },
  {
    id: 'p-012',
    name: 'JBL Flip 6 Bluetooth Speaker',
    slug: 'jbl-flip-6-speaker',
    shortDescription: '12hr playtime, IP67 waterproof',
    description:
      'Bold JBL Original Pro Sound with deep bass. 12 hours of playtime. IP67 waterproof and dustproof. PartyBoost-compatible for stereo sound.',
    category: CATEGORIES[5],
    brand: BRANDS[5],
    images: [img(PHOTOS.speaker), img(PHOTOS.sony)],
    variations: [
      {
        id: 'v-012-bk',
        productId: 'p-012',
        sku: 'FLIP6-BK',
        name: 'Black',
        sellingPrice: 119,
        mrp: 149,
        stock: 28,
        attributes: { Color: 'Black' },
        image: img(PHOTOS.speaker),
        isDefault: true,
      },
      {
        id: 'v-012-rd',
        productId: 'p-012',
        sku: 'FLIP6-RD',
        name: 'Red',
        sellingPrice: 119,
        mrp: 149,
        stock: 14,
        attributes: { Color: 'Red' },
        image: img(PHOTOS.speaker),
      },
    ],
    rating: 4.5,
    reviewCount: 234,
    isBestseller: true,
    isOnSale: true,
    freeShipping: true,
    estimatedDeliveryDays: 2,
  },
  {
    id: 'p-013',
    name: 'Organic Green Coffee Beans 500g',
    slug: 'organic-green-coffee-500g',
    shortDescription: 'Single origin, fair trade',
    description:
      'Premium single-origin green coffee beans from the highlands. Medium roast profile with notes of chocolate, citrus, and nuts. Fair trade certified.',
    category: CATEGORIES[11],
    brand: BRANDS[0],
    images: [img(PHOTOS.coffee), img(PHOTOS.snack)],
    variations: [
      {
        id: 'v-013-500',
        productId: 'p-013',
        sku: 'GRC-500',
        name: '500g - Whole Bean',
        sellingPrice: 25,
        mrp: 32,
        stock: 87,
        attributes: { Weight: '500g', Grind: 'Whole Bean' },
        image: img(PHOTOS.coffee),
        isDefault: true,
      },
    ],
    rating: 4.6,
    reviewCount: 89,
    isOnSale: true,
    freeShipping: false,
    estimatedDeliveryDays: 2,
  },
  {
    id: 'p-014',
    name: 'Luxe Velvet Sofa 3-Seater',
    slug: 'luxe-velvet-sofa-3-seater',
    shortDescription: 'Premium velvet, solid wood frame',
    description:
      'Statement 3-seater sofa upholstered in premium soft-touch velvet. Solid hardwood frame with high-density foam cushioning. Easy assembly. Multiple colors available.',
    category: CATEGORIES[12],
    brand: BRANDS[0],
    images: [img(PHOTOS.sofa), img(PHOTOS.lamp)],
    variations: [
      {
        id: 'v-014-em',
        productId: 'p-014',
        sku: 'LVS-3-EM',
        name: 'Emerald Green',
        sellingPrice: 1299,
        mrp: 1599,
        stock: 4,
        attributes: { Color: 'Emerald Green' },
        image: img(PHOTOS.sofa),
        isDefault: true,
      },
      {
        id: 'v-014-bk',
        productId: 'p-014',
        sku: 'LVS-3-BK',
        name: 'Midnight Black',
        sellingPrice: 1299,
        mrp: 1599,
        stock: 2,
        attributes: { Color: 'Midnight Black' },
        image: img(PHOTOS.sofa),
      },
    ],
    rating: 4.8,
    reviewCount: 23,
    isNew: true,
    isFeatured: true,
    freeShipping: true,
    estimatedDeliveryDays: 7,
  },
  {
    id: 'p-015',
    name: 'Minimalist Brass Desk Lamp',
    slug: 'minimalist-brass-desk-lamp',
    shortDescription: 'Adjustable arm, warm LED',
    description:
      'Sleek minimalist desk lamp in brushed brass finish. Adjustable arm and head. Warm 3000K LED with touch dimmer. USB-C charging port built in.',
    category: CATEGORIES[12],
    brand: BRANDS[0],
    images: [img(PHOTOS.lamp), img(PHOTOS.plant)],
    variations: [
      {
        id: 'v-015-br',
        productId: 'p-015',
        sku: 'MDL-BR',
        name: 'Brushed Brass',
        sellingPrice: 89,
        mrp: 119,
        stock: 21,
        attributes: { Color: 'Brushed Brass' },
        image: img(PHOTOS.lamp),
        isDefault: true,
      },
    ],
    rating: 4.7,
    reviewCount: 145,
    isFeatured: true,
    isNew: true,
    isOnSale: true,
    freeShipping: true,
    estimatedDeliveryDays: 3,
  },
  {
    id: 'p-016',
    name: 'Matte Lipstick - Rosewood',
    slug: 'matte-lipstick-rosewood',
    shortDescription: 'Long-lasting, hydrating formula',
    description:
      'Weightless matte finish that lasts 16 hours without drying. Enriched with vitamin E and jojoba oil for hydration. Cruelty-free and vegan.',
    category: CATEGORIES[13],
    brand: BRANDS[0],
    images: [img(PHOTOS.lipstick), img(PHOTOS.perfume)],
    variations: [
      {
        id: 'v-016-rw',
        productId: 'p-016',
        sku: 'MLP-RW',
        name: 'Rosewood',
        sellingPrice: 24,
        mrp: 32,
        stock: 64,
        attributes: { Shade: 'Rosewood' },
        image: img(PHOTOS.lipstick),
        isDefault: true,
      },
    ],
    rating: 4.4,
    reviewCount: 312,
    isBestseller: true,
    isOnSale: true,
    freeShipping: false,
    estimatedDeliveryDays: 2,
  },
];

export const REVIEWS: Review[] = [
  {
    id: 'r-1',
    productId: 'p-001',
    customerName: 'John D.',
    rating: 5,
    title: 'Excellent phone, fast delivery',
    body: 'The phone arrived in pristine condition with all original packaging. The titanium finish is gorgeous and the camera is unbelievable. Highly recommend this seller!',
    date: '2026-07-08',
    isVerifiedPurchase: true,
    helpfulCount: 24,
  },
  {
    id: 'r-2',
    productId: 'p-001',
    customerName: 'Sarah K.',
    rating: 4,
    title: 'Great but battery could be better',
    body: 'Phone is amazing and feels premium. The only downside is the battery life could be a bit longer with heavy use, but the fast charging makes up for it.',
    date: '2026-07-02',
    isVerifiedPurchase: true,
    helpfulCount: 12,
  },
  {
    id: 'r-3',
    productId: 'p-001',
    customerName: 'Mike R.',
    rating: 5,
    title: 'Worth every penny',
    body: 'Upgraded from iPhone 13 Pro. The difference is night and day. The Action button is incredibly useful and the USB-C port is a game changer.',
    date: '2026-06-28',
    isVerifiedPurchase: true,
    helpfulCount: 8,
  },
  {
    id: 'r-4',
    productId: 'p-004',
    customerName: 'David L.',
    rating: 5,
    title: 'Best noise cancellation',
    body: "These headphones are simply the best I've ever owned. The noise cancellation on flights is incredible. Comfortable for all-day wear.",
    date: '2026-07-05',
    isVerifiedPurchase: true,
    helpfulCount: 18,
  },
];

export const SAMPLE_ADDRESSES: Address[] = [
  {
    id: 'a-1',
    label: 'Home',
    name: 'John Doe',
    phone: '+880 1712-345678',
    addressLine1: 'House 12, Road 5',
    addressLine2: 'Dhanmondi',
    city: 'Dhaka',
    area: 'Dhanmondi',
    zipCode: '1205',
    country: 'Bangladesh',
    isDefault: true,
  },
  {
    id: 'a-2',
    label: 'Office',
    name: 'John Doe',
    phone: '+880 1712-345678',
    addressLine1: 'Level 7, Tower 2',
    addressLine2: 'Gulshan 2',
    city: 'Dhaka',
    area: 'Gulshan',
    zipCode: '1212',
    country: 'Bangladesh',
  },
];

export const SAMPLE_ORDERS: Order[] = [
  {
    id: 'o-1',
    orderNumber: 'ORD-2026-00123',
    uuid: 'ord-2026-00123-uuid',
    customerId: 'cu-1',
    items: [
      {
        variationId: 'v-001-256',
        productId: 'p-001',
        name: 'iPhone 15 Pro 256GB',
        slug: 'iphone-15-pro-256gb',
        image: img(PHOTOS.iphone15),
        unitPrice: 999,
        mrp: 1099,
        quantity: 1,
        attributes: { Storage: '256GB', Color: 'Natural Titanium' },
        stock: 15,
        lineTotal: 999,
      },
      {
        variationId: 'v-004-bk',
        productId: 'p-004',
        name: 'Sony WH-1000XM5 Wireless Headphones',
        slug: 'sony-wh-1000xm5',
        image: img(PHOTOS.sony),
        unitPrice: 349,
        quantity: 1,
        attributes: { Color: 'Black' },
        stock: 22,
        lineTotal: 349,
      },
    ],
    subtotal: 1348,
    shipping: 0,
    tax: 67.4,
    discount: 0,
    total: 1415.4,
    status: 'shipped',
    paymentStatus: 'paid',
    paymentMethod: 'bkash',
    shippingAddress: SAMPLE_ADDRESSES[0],
    shippingMethod: 'Standard Delivery',
    trackingNumber: 'SF-1234567',
    courier: 'Steadfast',
    createdAt: '2026-07-10T09:15:00Z',
    timeline: [
      { status: 'Placed', date: '2026-07-10 09:15', completed: true },
      { status: 'Confirmed', date: '2026-07-10 09:30', completed: true },
      { status: 'Packed', date: '2026-07-11 08:00', completed: true },
      { status: 'Shipped', date: '2026-07-11 16:00', completed: true },
      { status: 'Delivered', date: 'Expected Jul 13', completed: false },
    ],
  },
  {
    id: 'o-2',
    orderNumber: 'ORD-2026-00118',
    uuid: 'ord-2026-00118-uuid',
    customerId: 'cu-1',
    items: [
      {
        variationId: 'v-007-gy',
        productId: 'p-007',
        name: 'Logitech MX Master 3S',
        slug: 'logitech-mx-master-3s',
        image: img(PHOTOS.mouse),
        unitPrice: 99,
        quantity: 1,
        attributes: { Color: 'Graphite' },
        stock: 45,
        lineTotal: 99,
      },
    ],
    subtotal: 99,
    shipping: 60,
    tax: 4.95,
    discount: 0,
    total: 163.95,
    status: 'delivered',
    paymentStatus: 'paid',
    paymentMethod: 'cod',
    shippingAddress: SAMPLE_ADDRESSES[0],
    shippingMethod: 'Standard Delivery',
    createdAt: '2026-07-01T14:20:00Z',
    timeline: [
      { status: 'Placed', date: '2026-07-01 14:20', completed: true },
      { status: 'Confirmed', date: '2026-07-01 15:00', completed: true },
      { status: 'Packed', date: '2026-07-02 10:00', completed: true },
      { status: 'Shipped', date: '2026-07-02 16:00', completed: true },
      { status: 'Delivered', date: '2026-07-03 11:00', completed: true },
    ],
  },
  {
    id: 'o-3',
    orderNumber: 'ORD-2026-00130',
    uuid: 'ord-2026-00130-uuid',
    customerId: 'cu-1',
    items: [
      {
        variationId: 'v-005-usbc',
        productId: 'p-005',
        name: 'Apple AirPods Pro (2nd Gen)',
        slug: 'apple-airpods-pro-2',
        image: img(PHOTOS.airpods),
        unitPrice: 229,
        quantity: 1,
        attributes: { Case: 'USB-C MagSafe' },
        stock: 35,
        lineTotal: 229,
      },
    ],
    subtotal: 229,
    shipping: 0,
    tax: 11.45,
    discount: 0,
    total: 240.45,
    status: 'placed',
    paymentStatus: 'pending',
    paymentMethod: 'cod',
    shippingAddress: SAMPLE_ADDRESSES[0],
    shippingMethod: 'Express Delivery',
    createdAt: '2026-07-12T08:45:00Z',
    timeline: [
      { status: 'Placed', date: '2026-07-12 08:45', completed: true },
      { status: 'Confirmed', date: 'Pending', completed: false },
      { status: 'Packed', date: 'Pending', completed: false },
      { status: 'Shipped', date: 'Pending', completed: false },
      { status: 'Delivered', date: 'Pending', completed: false },
    ],
  },
];

export const SHIPPING_METHODS: ShippingMethod[] = [
  {
    id: 'ship-standard',
    name: 'Standard Delivery',
    description: 'Delivered in 2-3 business days',
    rate: 60,
    estimatedDays: '2-3 days',
  },
  {
    id: 'ship-express',
    name: 'Express Delivery',
    description: 'Next day delivery in major cities',
    rate: 150,
    estimatedDays: '1 day',
  },
  {
    id: 'ship-pickup',
    name: 'Store Pickup',
    description: 'Pick up from our Dhaka showroom',
    rate: 0,
    estimatedDays: 'Same day',
    isFree: true,
  },
];

export const PAYMENT_METHODS: PaymentMethod[] = [
  {
    id: 'pm-cod',
    name: 'Cash on Delivery',
    description: 'Pay when you receive your order',
    icon: 'Banknote',
    badge: 'Most popular',
  },
  {
    id: 'pm-bkash',
    name: 'bKash',
    description: 'Pay with your bKash mobile wallet',
    icon: 'Smartphone',
  },
  {
    id: 'pm-nagad',
    name: 'Nagad',
    description: 'Pay with your Nagad mobile wallet',
    icon: 'Smartphone',
  },
  {
    id: 'pm-card',
    name: 'Credit / Debit Card',
    description: 'Visa, Mastercard, AMEX via SSLCommerz',
    icon: 'CreditCard',
  },
  {
    id: 'pm-bank',
    name: 'Bank Transfer',
    description: 'Direct bank transfer to our account',
    icon: 'Building2',
  },
  {
    id: 'pm-sslcommerz',
    name: 'SSLCommerz',
    description: 'Pay with any local payment method',
    icon: 'Shield',
  },
];

export const COUPONS: Coupon[] = [
  {
    code: 'WELCOME10',
    type: 'percentage',
    value: 10,
    minOrderAmount: 1000,
    maxDiscountAmount: 500,
    description: '10% off on your first order',
    validUntil: '2026-12-31',
  },
  {
    code: 'FREESHIP',
    type: 'fixed',
    value: 60,
    description: 'Free shipping on any order',
    validUntil: '2026-12-31',
  },
  {
    code: 'SUMMER25',
    type: 'percentage',
    value: 25,
    minOrderAmount: 5000,
    maxDiscountAmount: 2000,
    description: '25% off - Summer sale',
    validUntil: '2026-08-31',
  },
];

export const HERO_BANNERS = [
  {
    id: 'b-1',
    title: 'iPhone 15 Pro',
    subtitle: 'Titanium. So strong. So light. So Pro.',
    description: 'Get up to ৳10,000 off with trade-in. Limited time offer.',
    image:
      'https://images.unsplash.com/photo-1696446702186-be9805d0f7b9?w=1600&h=900&fit=crop',
    cta: 'Shop Now',
    link: '/products/iphone-15-pro-256gb',
    accent: 'from-indigo-900/80 to-purple-900/60',
  },
  {
    id: 'b-2',
    title: 'Summer Sale',
    subtitle: 'Up to 50% off',
    description: 'Refresh your wardrobe with the season\u2019s hottest styles.',
    image:
      'https://images.unsplash.com/photo-1445205170230-053b83016050?w=1600&h=900&fit=crop',
    cta: 'Explore Fashion',
    link: '/category/fashion',
    accent: 'from-rose-900/80 to-pink-900/60',
  },
  {
    id: 'b-3',
    title: 'Smart Home Upgrade',
    subtitle: 'Tech that simplifies life',
    description: 'From speakers to laptops — premium electronics at the best prices.',
    image:
      'https://images.unsplash.com/photo-1593344484962-796055d4a3a4?w=1600&h=900&fit=crop',
    cta: 'Discover Electronics',
    link: '/category/electronics',
    accent: 'from-slate-900/80 to-blue-900/60',
  },
];

export const PROMO_BANNERS = [
  {
    id: 'pb-1',
    title: 'Free Shipping',
    subtitle: 'On orders over ৳5,000',
    image:
      'https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55?w=800&h=400&fit=crop',
    link: '/products',
    accent: 'bg-emerald-600',
  },
  {
    id: 'pb-2',
    title: 'New Arrivals',
    subtitle: 'Latest collection just dropped',
    image:
      'https://images.unsplash.com/photo-1491637639811-60e2756cc1c7?w=800&h=400&fit=crop',
    link: '/products?filter=new',
    accent: 'bg-indigo-600',
  },
];

export const POPULAR_SEARCHES = [
  'iphone 15',
  'wireless earbuds',
  'laptop bag',
  'running shoes',
  'smart watch',
  'usb-c cable',
  'coffee maker',
  'lipstick',
];
