import apiClient from '@/lib/api/axios';
import type { ApiResponse, BulkImportResult } from '@/types/api.types';

// Bulk import payload types live in @/types/api.types — they are shared with
// customerService and every other /bulk-import/* caller.
export type { BulkImportResult, BulkImportRowError, BulkImportStats } from '@/types/api.types';

export interface Supplier {
  id: string;
  uuid?: string;
  tenant_id?: string;
  code: string;
  name: string;
  company_name?: string;
  contact_person?: string;
  phone?: string;
  email?: string;
  address?: string;
  city?: string;
  state?: string;
  country?: string;
  postal_code?: string;
  vat_number?: string;
  tin_number?: string;
  trade_license?: string;
  credit_limit?: number;
  current_balance?: number;
  payment_terms?: string;
  status?: string;
}

class SupplierService {
  async getSuppliers(params?: Record<string, any>) {
    const response = await apiClient.get<ApiResponse<any>>('/api/v1/suppliers', { params });
    return response.data.data;
  }

  async storeSupplier(data: Record<string, any>) {
    const response = await apiClient.post<ApiResponse<any>>('/api/v1/suppliers/store', data);
    return response.data.data;
  }

  async deleteSupplier(id: string) {
    await apiClient.get(`/api/v1/suppliers/delete/${id}`);
  }

  /**
   * Download supplier sample Excel template
   * GET /api/v1/bulk-import/suppliers/sample-excel
   *
   * Two columns only — Name and Mobile No. Supplier codes are generated by the
   * backend (SP1001, SP1002, ...), so there is no Code column to fill in.
   * tenantId is optional and only read by the API for super admins; everyone
   * else gets their own tenant.
   */
  async downloadSupplierSampleExcel(tenantId?: string | null): Promise<void> {
    const response = await apiClient.get('/api/v1/bulk-import/suppliers/sample-excel', {
      params: tenantId ? { tenant_id: tenantId } : undefined,
      responseType: 'blob',
    });

    const url = window.URL.createObjectURL(new Blob([response.data]));
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `supplier_bulk_upload_template_${new Date().toISOString().split('T')[0]}.xlsx`);
    document.body.appendChild(link);
    link.click();
    link.remove();
    window.URL.revokeObjectURL(url);
  }

  /**
   * Bulk import suppliers from an Excel or CSV file
   * POST /api/v1/bulk-import/suppliers
   *
   * Rejects with a 422 whose body is `{ message, errors: BulkImportRowError[] }`
   * when spreadsheet rows fail validation, so the caller must read errors off
   * the axios error rather than the resolved value.
   */
  async supplierBulkImport(file: File, tenantId?: string | null): Promise<BulkImportResult> {
    const formData = new FormData();
    formData.append('file', file);
    if (tenantId) formData.append('tenant_id', tenantId);

    const response = await apiClient.post<BulkImportResult>('/api/v1/bulk-import/suppliers', formData, {
      headers: { 'Content-Type': 'multipart/form-data' },
    });

    return response.data;
  }
}

export default new SupplierService();
